/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  IMovie,
} from './components/stencil-movie-card/stencil-movie-card';

export namespace Components {
  interface StencilMovieCard {
    'movie': IMovie;
  }
}

declare global {


  interface HTMLStencilMovieCardElement extends Components.StencilMovieCard, HTMLStencilElement {}
  var HTMLStencilMovieCardElement: {
    prototype: HTMLStencilMovieCardElement;
    new (): HTMLStencilMovieCardElement;
  };
  interface HTMLElementTagNameMap {
    'stencil-movie-card': HTMLStencilMovieCardElement;
  }
}

declare namespace LocalJSX {
  interface StencilMovieCard extends JSXBase.HTMLAttributes<HTMLStencilMovieCardElement> {
    'movie'?: IMovie;
  }

  interface IntrinsicElements {
    'stencil-movie-card': StencilMovieCard;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


