/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  IMovie,
} from './components/stencil-video-placeholder/stencil-video-placeholder';

export namespace Components {
  interface StencilVideoPlaceholder {
    'movie': IMovie;
  }
}

declare global {


  interface HTMLStencilVideoPlaceholderElement extends Components.StencilVideoPlaceholder, HTMLStencilElement {}
  var HTMLStencilVideoPlaceholderElement: {
    prototype: HTMLStencilVideoPlaceholderElement;
    new (): HTMLStencilVideoPlaceholderElement;
  };
  interface HTMLElementTagNameMap {
    'stencil-video-placeholder': HTMLStencilVideoPlaceholderElement;
  }
}

declare namespace LocalJSX {
  interface StencilVideoPlaceholder extends JSXBase.HTMLAttributes<HTMLStencilVideoPlaceholderElement> {
    'movie'?: IMovie;
  }

  interface IntrinsicElements {
    'stencil-video-placeholder': StencilVideoPlaceholder;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


